package com.financiera.dto;

import com.financiera.model.TransactionType;
import com.financiera.model.TransactionStatus;
import lombok.Data;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

/**
 * DTO used for responding to client requests (GET, POST, PUT).
 * Includes all read-only fields generated by the system (ID, timestamp, status).
 */
@Data
public class TransactionResponse {

    private UUID transactionId;
    private String accountId;
    private TransactionType type;
    private BigDecimal amount;
    private String currency;
    private String description;
    private Instant timestamp;
    private TransactionStatus status;
    
}